name: Deploy Lambda via SAM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install AWS SAM CLI
      run: |
        pip install aws-sam-cli

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: SAM Build
      run: sam build

    - name: SAM Deploy
      run: |
        sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
          --stack-name my-lambda-stack \
          --capabilities CAPABILITY_IAM \
          --region ap-northeast-2
